name: AutoRelease

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: g++ -pthread main.cpp -o tetris.out
      - uses: actions/checkout@v2
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: "Release: $version"
          tag: "release"
          draft: false
          regex: "/^Release: #{release}$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
