name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: SkullofGods
    - name: install
      run: g++ -pthread main.cpp -o tetris.out
    
  integration-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: SkullofGods/Tetris_inside_console@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        title: ${{ github.sha }}

  release:
    runs-on: ubuntu-latest
    needs:
      - integration-test
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }} # for pushing to protected branch
      - name: Publish new version
        run: |
          hub release create -m "AutoRelease" "$(date +%Y%m%d%H%M%S)"
          git config --global user.email "salahtinov.ilua2010.ru@gmail.com"
          git config --global user.name "Release Bot"
          git tag -fa v4 -m "Update v4 tag"
          git push origin v4 --force
